In [4]:
import numpy as np
import sympy as sp


# BÀI 1

In [3]:
A = sp.Matrix([[1, 2], [3, 1]])
B = sp.Matrix([[1, 0, 2], [3, 1, -2]])
C = sp.Matrix([[1, -2, 3], [-2, 1, -1]])
D = sp.Matrix([[-2], [2], [1]])

In [8]:
A * B

Matrix([
[7, 2, -2],
[6, 1,  4]])

In [10]:
A * (3*B + C)

Matrix([
[18,  6, -5],
[19, -2, 20]])

In [12]:
A * B * C

ShapeError: Matrix size mismatch: (2, 3) * (2, 3).

In [13]:
A * B * D

Matrix([
[-12],
[ -6]])

In [15]:
B.transpose() * A

Matrix([
[10, 5],
[ 3, 1],
[-4, 2]])

In [16]:
B * C.transpose()

Matrix([
[ 7, -4],
[-5, -3]])

# BÀI 2

In [19]:
A = sp.Matrix([[1,2,1], [3,7,3], [2,3,4]])

Matrix([
[1, 2, 1],
[3, 7, 3],
[2, 3, 4]])

In [20]:
A.det()

2

In [21]:
A.inv()

Matrix([
[19/2, -5/2, -1/2],
[  -3,    1,    0],
[-5/2,  1/2,  1/2]])

In [29]:
B = sp.Matrix([[1,-1,2], [1,1,-2], [1,1,4]])
B

Matrix([
[1, -1,  2],
[1,  1, -2],
[1,  1,  4]])

In [30]:
B.det()

12

In [31]:
B.inv()

Matrix([
[ 1/2,  1/2,   0],
[-1/2,  1/6, 1/3],
[   0, -1/6, 1/6]])

# Bài 3

In [7]:
x = np.array([1, 2, 3])
# create vector y = [y1, y2, y3]
y = np.array(['y1', 'y2', 'y3'])
z = np.array([4, 2, 1])

In [13]:
# calculate 2x - 3y
np.dot(x, z)

11

In [21]:
x1 = x.astype('S')
z1 = z.astype('S')
y1 = y.astype('S')

In [24]:
np.sqrt(x.dot(x))

3.7416573867739413

# Bài 4


In [27]:
A = sp.Matrix([[1,1,2,0], [2,0,1,0], [-1,2,1,0]])

(Matrix([
 [1, 0, 0, 0],
 [0, 1, 0, 0],
 [0, 0, 1, 0]]),
 (0, 1, 2))

# Bài 6

In [71]:
v1 = np.array([1,2,1])
v2 = np.array([1,-2,1])
v3 = np.array([1,2,-1])

In [46]:
q1 = np.array([1/np.sqrt(6), 2/np.sqrt(6), 1/np.sqrt(6)])
q2 = np.array([1/np.sqrt(3), -1/np.sqrt(3), 1/np.sqrt(3)])
q3 = np.array([3/np.sqrt(22), -2/np.sqrt(22), -3/np.sqrt(22)])

In [76]:
import sympy as sp
A = sp.Matrix([[1,1,1], [2,-2,2], [1,1,-1]])

A.QRdecomposition()

(Matrix([
 [sqrt(6)/6,  sqrt(3)/3,  sqrt(2)/2],
 [sqrt(6)/3, -sqrt(3)/3,          0],
 [sqrt(6)/6,  sqrt(3)/3, -sqrt(2)/2]]),
 Matrix([
 [sqrt(6),  -sqrt(6)/3,  2*sqrt(6)/3],
 [      0, 4*sqrt(3)/3, -2*sqrt(3)/3],
 [      0,           0,      sqrt(2)]]))

In [102]:
v1 = np.array([1,2,3,0])
v2 = np.array([1,2,0,0])
v3 = np.array([1,0,0,1])

mag1 = np.sqrt(v1.dot(v1))


u2 = v2 - ((v2.dot(v1))/mag1**2) * v1
u2

array([ 0.64285714,  1.28571429, -1.07142857,  0.        ])

In [98]:
A = sp.Matrix([[1,1,1], [2,2,0], [3,0,0], [0,0,1]])
A.QRdecomposition()

(Matrix([
 [  sqrt(14)/14, 3*sqrt(70)/70,  4*sqrt(5)/15],
 [   sqrt(14)/7, 3*sqrt(70)/35, -2*sqrt(5)/15],
 [3*sqrt(14)/14,  -sqrt(70)/14,             0],
 [            0,             0,     sqrt(5)/3]]),
 Matrix([
 [sqrt(14), 5*sqrt(14)/14,   sqrt(14)/14],
 [       0, 3*sqrt(70)/14, 3*sqrt(70)/70],
 [       0,             0,   3*sqrt(5)/5]]))

In [106]:
v1 = np.array([1,1,-1,0])
v2 = np.array([-1,0,1,1])
v3 = np.array([2,-1,2,1])

mag1 = np.sqrt(v1.dot(v1))

u2 = v2 - ((v2.dot(v1))/mag1**2) * v1
u2 = u2 * 3
u2

array([-1.,  2.,  1.,  3.])

In [113]:
mag2 = np.sqrt(u2.dot(u2))

u3 = v3 - (v3.dot(v1)/mag1**2) * v1 - (v3.dot(u2)/mag2**2) * u2
print(u3)
u3 *= 5/4
print(u3)

[ 2.4 -0.8  1.6  0.8]
[ 3. -1.  2.  1.]


In [138]:
A = sp.Matrix([[1,-1,2], [1,0,-1], [-1,1,2], [0,1,1]])
A

Matrix([
[ 1, -1,  2],
[ 1,  0, -1],
[-1,  1,  2],
[ 0,  1,  1]])

In [139]:
A.QRdecomposition()

(Matrix([
 [ sqrt(3)/3,  -sqrt(15)/15,    sqrt(15)/5],
 [ sqrt(3)/3, 2*sqrt(15)/15,  -sqrt(15)/15],
 [-sqrt(3)/3,   sqrt(15)/15, 2*sqrt(15)/15],
 [         0,    sqrt(15)/5,   sqrt(15)/15]]),
 Matrix([
 [sqrt(3), -2*sqrt(3)/3,   -sqrt(3)/3],
 [      0,   sqrt(15)/3,  sqrt(15)/15],
 [      0,            0, 4*sqrt(15)/5]]))

In [141]:
v1 = np.array([-1,1,-1,1])
v2 = np.array([-1,3,-1,3])
v3 = np.array([1,3,5,7])

mag1 = np.sqrt(v1.dot(v1))

u2 = v2 - ((v2.dot(v1))/mag1**2) * v1
u2

array([1., 1., 1., 1.])

In [143]:
mag2 = np.sqrt(u2.dot(u2))

u3 = v3 - (v3.dot(v1)/mag1**2) * v1 - (v3.dot(u2)/mag2**2) * u2
u3

array([-2., -2.,  2.,  2.])

In [151]:
# create column vectors matrix v1, v2, v3
A = sp.Matrix([[-1,-1,1], [1,3,3], [-1,-1,5], [1,3,7]])

In [152]:
A.QRdecomposition()

(Matrix([
 [-1/2, 1/2, -1/2],
 [ 1/2, 1/2, -1/2],
 [-1/2, 1/2,  1/2],
 [ 1/2, 1/2,  1/2]]),
 Matrix([
 [2, 4, 2],
 [0, 2, 8],
 [0, 0, 4]]))

In [154]:
A = sp.Matrix([[1,1,2], [2,-1,1], [-2,4,1]])
A.QRdecomposition()

(Matrix([
 [ 1/3, 2/3,  2/3],
 [ 2/3, 1/3, -2/3],
 [-2/3, 2/3, -1/3]]),
 Matrix([
 [3, -3, 2/3],
 [0,  3, 7/3],
 [0,  0, 1/3]]))

In [155]:
A = sp.Matrix([[1,1,-1], [0,1,2], [1,1,1]])
A.QRdecomposition()

(Matrix([
 [sqrt(2)/2, 0, -sqrt(2)/2],
 [        0, 1,          0],
 [sqrt(2)/2, 0,  sqrt(2)/2]]),
 Matrix([
 [sqrt(2), sqrt(2),       0],
 [      0,       1,       2],
 [      0,       0, sqrt(2)]]))

In [156]:
A = sp.Matrix([[-2,1,3], [1,0,0], [0,1,0], [0,0,1]])
A.QRdecomposition()

(Matrix([
 [-2*sqrt(5)/5, sqrt(30)/30,  sqrt(10)/10],
 [   sqrt(5)/5, sqrt(30)/15,   sqrt(10)/5],
 [           0,  sqrt(30)/6, -sqrt(10)/10],
 [           0,           0,   sqrt(10)/5]]),
 Matrix([
 [sqrt(5), -2*sqrt(5)/5, -6*sqrt(5)/5],
 [      0,   sqrt(30)/5,  sqrt(30)/10],
 [      0,            0,   sqrt(10)/2]]))