In [1]:
import numpy as np

In [19]:
img_1d = np.array([[[235, 255, 255], [215, 0, 0], [252, 0, 0], [255, 0, 0], [255, 255, 255]],
                     [[255, 255, 255], [255, 0, 0], [255, 255, 255], [255, 0, 0], [255, 255, 255]],
                     [[255, 255, 255], [255, 0, 0], [255, 255, 255], [255, 0, 0], [255, 255, 255]],
                     [[255, 255, 255], [255, 0, 0], [255, 255, 255], [255, 0, 0], [255, 255, 255]],
                     [[255, 255, 255], [255, 0, 0], [255, 0, 0], [255, 0, 0], [255, 255, 255]]])
img_1d = img_1d.reshape(img_1d.shape[0] * img_1d.shape[1], 3)

In [20]:
unique_img_1d = np.unique(img_1d, axis=0)
index_array = np.random.choice(unique_img_1d.shape[0], 3, replace=False)
display(index_array)
for color in index_array:
    print(img_1d[color])

array([0, 4, 1])

[235 255 255]
[255 255 255]
[215   0   0]


In [35]:
img = np.array([[10, 20, 30],
               [40, 50, 60],
               [70, 80, 90]])

centroid = np.array([[1, 2, 3],
                    [4, 5, 6]])

# centroid = np.array([[1, 2, 3]])
num = 3
# img = img.reshape(len(img), 1, num)
# centroid = centroid.reshape(1, len(centroid), num)

img = img[:,None]
centroid = centroid[None,:]
# print((img - centroid) ** 2)
# print(np.sum((img - centroid) ** 2, axis=-1))
# print(np.argmin(np.sum((img - centroid) ** 2, axis=-1), axis=-1))
print(img.shape)
print(centroid.shape)

(3, 1, 3)
(1, 2, 3)
