In [2]:
import numpy as np

In [24]:
A = np.array([[1, 1, 1]])
B = np.array([[0.393, 0.769, 0.189], [0.349, 0.686, 0.168], [0.272, 0.534, 0.131]])
print(B.T)

[[0.393 0.349 0.272]
 [0.769 0.686 0.534]
 [0.189 0.168 0.131]]


In [23]:
display(np.dot(A, B.T))

array([[1.351, 1.203, 0.937]])