In [3]:
import numpy as np

In [4]:
img_1d = np.array([[[235, 255, 255], [215, 0, 0], [252, 0, 0], [255, 0, 0], [255, 255, 255]],
                     [[255, 255, 255], [255, 0, 0], [255, 255, 255], [255, 0, 0], [255, 255, 255]],
                     [[255, 255, 255], [255, 0, 0], [255, 255, 255], [255, 0, 0], [255, 255, 255]],
                     [[255, 255, 255], [255, 0, 0], [255, 255, 255], [255, 0, 0], [255, 255, 255]],
                     [[255, 255, 255], [255, 0, 0], [255, 0, 0], [255, 0, 0], [255, 255, 255]]])
img_1d = img_1d.reshape(img_1d.shape[0] * img_1d.shape[1], 3)

In [5]:
unique_img_1d = np.unique(img_1d, axis=0)
index_array = np.random.choice(unique_img_1d.shape[0], 3, replace=False)
display(index_array)
for color in index_array:
    print(img_1d[color])

array([2, 4, 0])

[252   0   0]
[255 255 255]
[235 255 255]


In [9]:
img = np.array([[10, 20, 30],
               [40, 50, 60],
               [70, 80, 90]])

centroid = np.array([[1, 2, 3],
                    [4, 5, 6]])

# centroid = np.array([[1, 2, 3]])
num = 3
# img = img.reshape(len(img), 1, num)
# centroid = centroid.reshape(1, len(centroid), num)

img = img[:,None]
centroid = centroid[None,:]

display(img)
display(centroid)

print(img - centroid)
print((img - centroid) ** 2)
print(np.sum((img - centroid) ** 2, axis=-1))
print(np.argmin(np.sum((img - centroid) ** 2, axis=-1), axis=-1))
print(img.shape)
print(centroid.shape)

array([[[10, 20, 30]],

       [[40, 50, 60]],

       [[70, 80, 90]]])

array([[[1, 2, 3],
        [4, 5, 6]]])

[[[ 9 18 27]
  [ 6 15 24]]

 [[39 48 57]
  [36 45 54]]

 [[69 78 87]
  [66 75 84]]]
[[[  81  324  729]
  [  36  225  576]]

 [[1521 2304 3249]
  [1296 2025 2916]]

 [[4761 6084 7569]
  [4356 5625 7056]]]
[[ 1134   837]
 [ 7074  6237]
 [18414 17037]]
[1 1 1]
(3, 1, 3)
(1, 2, 3)


In [ ]:
def initialize_centroids(img_1d, k_clusters, init_centroids):
    unique_img_1d = np.unique(img_1d, axis=0)
    k_clusters = min(k_clusters, len(unique_img_1d))
    if init_centroids == 'random':
        centroids = np.random.randint(256, size=(k_clusters, img_1d.shape[1]), dtype='uint8')
    elif init_centroids == 'in_pixels':
        index_array = np.random.choice(unique_img_1d.shape[0], k_clusters, replace=False)
        centroids = [unique_img_1d[index_array[i]] for i in range(k_clusters)]
    else:
        raise ValueError('init_centroids must be "random" or "in_pixels"')
    return np.array(centroids)